### ISSUE TITLE
How secure does `server-token` need to be?

### ISSUE THREAD

**Issue by moltar** [felixmosh/turborepo-gh-artifacts#1]
I am guessing this isn't a big deal to have something random there?

I am thinking to set this to the value of `RUNNER_TEMP`, which is a temporary dir within which the project is being built. This dir is random and unpredictable ahead of time.

See https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by felixmosh** [comment]
It doesn't matter, it just makes sure that the "thing" that interactive with the local server is comes from "known" source.

It can contain any value, even "" (empty string) :]

**Comment by moltar** [comment]
Thanks, I assumed so, but the use of `${{ secrets.` had threw me off :)

**Comment by moltar** [comment]
Btw, incorporating it here: https://github.com/moltar/projen-turborepo
