### ISSUE TITLE
docs: example TurboRepo cli team flag

### ISSUE THREAD

**Issue by johnhooks** [felixmosh/turborepo-gh-artifacts#17]
Is the team flag to TurboRepo irrelevant, just fill TurboRepo cli expectations?

I don't see any where that the local server created by this action uses it.

**Comment by felixmosh** [comment]
That's true, there is no usage of it

**Comment by johnhooks** [comment]
Thanks for the quick response!

**Comment by felixmosh** [comment]
Do you think that there is some usage for it?

**Comment by johnhooks** [comment]
Check out this new issue #18
