### ISSUE TITLE
Cache missed in private repo

### ISSUE THREAD

**Issue by elpddev** [felixmosh/turborepo-gh-artifacts#23]
Thank you for a great project. Great idea and work.

I had a problem getting the action to work under a private repository. Every time the cache was reported missed. It seems the [list artifact](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#list-artifacts-for-a-repository) api returned soft error each activation. It did not throw.

https://github.com/felixmosh/turborepo-gh-artifacts/blob/a73d2a81585ca9fb37c3a22070c4bc809b93dc6b/src/turboServer.ts#L51 

```json
{
  "message":"Resource not accessible by integration",
  "documentation_url":"https://docs.github.com/rest/reference/actions#list-artifacts-for-a-repository"
}
```

Eventually it seems the GITHUB_TOKEN is not enough in private repos. You need to create a private api token with the "repository" permission to be able to use the endpoint.

>  If the repository is private you must use an access token with the repo scope.

I'm not sure why the call did not throw. Maybe Github does not return error for this case. Maybe a check can be added to guard against it. Regardless, it works very well now with the correct token.

**Comment by felixmosh** [comment]
Hi @elpddev, there is a node in the [README](https://github.com/felixmosh/turborepo-gh-artifacts#action-inputs) that the token most have `repo` permissions.

You are right, GitHub API returns 200 with an error message, I've added a print of this error, hope that it will direct the next user into the right direction :]

Thank you for reporting this issue 🙏🏼
