### ISSUE TITLE
Pull artifacts by name

### ISSUE THREAD

**Issue by Ugzuzg** [felixmosh/turborepo-gh-artifacts#25]
[List artifacts for a repository](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#list-artifacts-for-a-repository) endpoint supports querying by `name`.

In a big monorepo, having only 100 last uploaded artifacts creates a lot of rebuilds due to a big number of artifacts uploaded. Looking for an artifact by its name would improve the situation.

Happy to submit a PR.

**Comment by felixmosh** [comment]
You are absolutely right, this is a wierd decision on my part (I don't remember the reason for this).
Let me poke around, to check if that will work.

**Comment by Ugzuzg** [comment]
Thanks for a quick resolution! Works perfectly.
