### ISSUE TITLE
Cache artifacts not found

### ISSUE THREAD

**Issue by moltar** [felixmosh/turborepo-gh-artifacts#5]
I think there is indeed an issue with artifact discovery. Maybe that's why array is undefined.

I am seeing cache misses, yet I do see the artifact with the same name listed in the API.

And after a run, there are 2 artifacts now with the same name.

**Comment by felixmosh** [comment]
Can you make a repo that reproduces the issue?

**Comment by smeebear** [comment]
@moltar If you're having these issues inside a private repo, verify that your workflow has the `actions: read` permissions. I was seeing artifacts with the same hashes being generated on each run of my workflow, and now it properly recognizes them as a hit!

[Source](https://docs.github.com/en/rest/reference/actions#get-an-artifact)

**Comment by felixmosh** [comment]
@moltar does it help? If so, I'll add a comment in the readme 🙏🏼

**Comment by moltar** [comment]
@smeebear thanks for the tip! This indeed had solved the issue! :)
