### ISSUE TITLE
`outputs: []` not cached

### ISSUE THREAD

**Issue by humphd** [felixmosh/turborepo-gh-artifacts#6]
We're trying to use `turborepo-gh-artifacts` in a workflow, and we've got it integrated, but it never caches anything for our lint/tests:

```sh
Post job cleanup.
Found server pid: 1881
Killing server pid: 1881
There is nothing to upload.
Server logs:
Cache dir: /home/runner/work/_temp/turbo-cache
Local Turbo server is listening at http://127.0.0.1:9080
```

Looking at your [example run](https://github.com/felixmosh/turborepo-gh-artifacts-example/runs/4831275828?check_suite_focus=true), it's clear that it is uploading cache items.  However, you're also calling `build` vs. `lint`, which is what we're trying to do (i.e., run tests).

From the [Turbo Repo docs](https://turborepo.org/docs/features/caching#:~:text=If%20your%20task%20does%20not%20emit%20any%20files%20(e.g.%20unit%20tests%20with%20Jest)%2C%20set%20outputs%20to%20an%20empty%20array%20(i.e.%20%5B%5D).%20Turborepo%20will%20automagically%20cache%20the%20logs%20for%20you), it implies that such tasks would still get cached:

> If your task does not emit any files (e.g. unit tests with Jest), set outputs to an empty array (i.e. []). Turborepo will automagically cache the logs for you.

Your code appears to assume there will be a file produced: https://github.com/felixmosh/turborepo-gh-artifacts/blob/master/src/utils/uploadArtifacts.ts#L33-L44

Is this a bug, or confusion on our part?

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue 🙏

From your server logs looks like turbo didn't approached to the server (when it does, there are get / put requests)

I in my app there is a lint stage, and its logs are cached.

Let me test it again, and I will update here

**Comment by felixmosh** [comment]
I've tested it, it works properly, 
https://github.com/felixmosh/turborepo-gh-artifacts-example/actions/runs/2167137139

Theses 2 artifacts are for the lint output.

Pay ❤️, `GITHUB_TOKEN` must have [actions: read](https://docs.github.com/en/rest/reference/actions#get-an-artifact) permissions in order to be able to read repo's existing artifacts.

**Comment by humphd** [comment]
Ok, I'll debug some more.  I can't see what we're missing, based on your example.  Thanks for checking.

**Comment by felixmosh** [comment]
Any updates?

**Comment by humphd** [comment]
cc @menghif.  I haven't had time to debug further, but it's not working for us.

**Comment by felixmosh** [comment]
Can you (or @menghif) prepare a repo that reproduces the issue?

**Comment by humphd** [comment]
You can see it in https://github.com/Seneca-CDOT/telescope, for example, the eslint workflow at https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/eslint-ci.yml or unit tests at https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/unit-tests-ci.yml.

Some runs:

- https://github.com/Seneca-CDOT/telescope/runs/6099737891?check_suite_focus=true
- https://github.com/Seneca-CDOT/telescope/runs/6099738354?check_suite_focus=true

**Comment by felixmosh** [comment]
Can you add the team flag as well.
If I recall properly, without it the remote caching is not enabled.

**Comment by menghif** [comment]
I added the team flag and it now works. Thank you very much @felixmosh for your help!

Since in the [Turborepo docs](https://turborepo.org/docs/features/remote-caching#custom-remote-caches) the team flag is not present, I assumed it was not required. Would it be possible to update the README page for this project?

**Comment by humphd** [comment]
I wonder if the reason I missed this, is that GitHub cuts it off, so I visually skimmed over it:

<img width="906" alt="Screen Shot 2022-04-22 at 11 30 44 AM" src="https://user-images.githubusercontent.com/427398/164746531-d6b6c520-9cc9-4a9e-97f3-147d6419eaa9.png">

It might be good to call out the args explicitly.

Thanks for making this @felixmosh, it's so cool to have it finally working in our repo!

**Comment by felixmosh** [comment]
Glad it helped you. :)

**Comment by felixmosh** [comment]
Can I close this issue?

**Comment by humphd** [comment]
Yes, thanks for all the help with this.
