### ISSUE TITLE
License for using and contributing

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [felixmosh/turborepo-gh-artifacts#8]
In order to be able to use the content here and even contribute to it, we need a license statement which provides usage rights. Due to the copyright laws, there is currently no right to use the content of this repo for anyone else than the copyright owner. 

Since there is a mentioning of MIT in the package.json where it is unclear, what is meant by it, I recommend to add a standard MIT license text with the copyright addition typical for the license. Afterwards, add a section in the README that states that the usage is licensed by MIT and that contributions have to be done under the MIT license as well.

I saw, that there is one additional contributor to the repository. To play this legal, I recommend to get his agreement on the license.

**Comment by blaumeiser-at-bosch** [comment]
@felixmosh Could you please give feedback whether you do the necessary changes or not, as we would really like to make use of this but have to abandon the implementation and redo it if we do not get any rights to use it.

**Comment by felixmosh** [comment]
Sure thing, sorry for missing this out, it is MIT as stated in the `package.json` file :]

I've added License file as Github recommends.

**Comment by blaumeiser-at-bosch** [comment]
Thank you so much, @felixmosh
